package edu.pitt.cs;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.MatcherAssert.assertThat;
import org.junit.FixMethodOrder;
import org.junit.runners.MethodSorters;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class D3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tEST1LINKS() {
    // Open the target URL
    driver.get("http://localhost:8080");
    // Set cookies to false
    js.executeScript("document.cookie = \'1=false\';document.cookie = \'2=false\';document.cookie = \'3=false\';");
    // Check Reset link exists
    {
      List<WebElement> elements = driver.findElements(By.linkText("Reset"));
      assert(elements.size() > 0);
    }
    // Check Reset link href contains /reset
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("a[href*=\'/reset\']"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST2RESET() {
    // Open the target URL
    driver.get("http://localhost:8080");
    // Set cookies to true (cats are rented)
    js.executeScript("document.cookie = \'1=true\';document.cookie = \'2=true\';document.cookie = \'3=true\';");
    // Press the Reset link
    driver.findElement(By.linkText("Reset")).click();
    // Check first cat is available
    assertThat(driver.findElement(By.cssSelector("#listing li:nth-child(1)")).getText(), is("ID 1. Jennyanydots"));
    // Check second cat is available
    assertThat(driver.findElement(By.cssSelector("#listing li:nth-child(2)")).getText(), is("ID 2. Old Deuteronomy"));
    // Check third cat is available
    assertThat(driver.findElement(By.cssSelector("#listing li:nth-child(3)")).getText(), is("ID 3. Mistoffelees"));
  }
  @Test
  public void tEST3CATALOG() {
    // Open the target URL
    driver.get("http://localhost:8080");
    // Set cookies to false
    js.executeScript("document.cookie = \'1=false\';document.cookie = \'2=false\';document.cookie = \'3=false\';");
    // Press the Catalog link
    driver.findElement(By.linkText("Catalog")).click();
    // Check second image is cat2.jpg
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("img[src*=\'/images/cat2.jpg\']"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST4LISTING() {
    // Open the target URL
    driver.get("http://localhost:8080");
    // Set cookies to false
    js.executeScript("document.cookie = \'1=false\';document.cookie = \'2=false\';document.cookie = \'3=false\';");
    // Press the Catalog link
    driver.findElement(By.linkText("Catalog")).click();
    // Check third item is ID 3. Mistoffelees
    assertThat(driver.findElement(By.cssSelector("#listing li:nth-child(3)")).getText(), is("ID 3. Mistoffelees"));
  }
  @Test
  public void tEST5RENTACAT() {
    // Open the target URL
    driver.get("http://localhost:8080");
    // Set cookies to false
    js.executeScript("document.cookie = \'1=false\';document.cookie = \'2=false\';document.cookie = \'3=false\';");
    // Press the Rent-A-Cat link
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    // Check Rent button exists
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[contains(text(), \'Rent\')]"));
      assert(elements.size() > 0);
    }
    // Check Return button exists
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[contains(text(), \'Return\')]"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST6RENT() {
    // Open the target URL
    driver.get("http://localhost:8080");
    // Set cookies to false
    js.executeScript("document.cookie = \'1=false\';document.cookie = \'2=false\';document.cookie = \'3=false\';");
    // Press the Rent-A-Cat link
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    // Enter 1 into rent input
    driver.findElement(By.id("rentID")).sendKeys("1");
    // Press the Rent button
    driver.findElement(By.xpath("//button[contains(text(), \'Rent\')]")).click();
    // Check first cat is rented out
    assertThat(driver.findElement(By.cssSelector("#listing li:nth-child(1)")).getText(), is("Rented out"));
    // Check Success message
    assertThat(driver.findElement(By.id("rentResult")).getText(), is("Success!"));
  }
  @Test
  public void tEST7RETURN() {
    // Open the target URL
    driver.get("http://localhost:8080");
    // Set cookie 2 to true (cat ID 2 is rented)
    js.executeScript("document.cookie = \'2=true\';");
    // Press the Rent-A-Cat link
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    // Enter 2 into return input
    driver.findElement(By.id("returnID")).sendKeys("2");
    // Press the Return button
    driver.findElement(By.xpath("//button[contains(text(), \'Return\')]")).click();
    // Check second cat is available
    assertThat(driver.findElement(By.cssSelector("#listing li:nth-child(2)")).getText(), is("ID 2. Old Deuteronomy"));
    // Check Success message
    assertThat(driver.findElement(By.id("returnResult")).getText(), is("Success!"));
  }
  @Test
  public void tEST8FEEDACAT() {
    // Open the target URL
    driver.get("http://localhost:8080");
    // Set cookies to false
    js.executeScript("document.cookie = \'1=false\';document.cookie = \'2=false\';document.cookie = \'3=false\';");
    // Press the Feed-A-Cat link
    driver.findElement(By.linkText("Feed-A-Cat")).click();
    // Check Feed button exists
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[contains(text(), \'Feed\')]"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST9FEED() {
    // Open the target URL
    driver.get("http://localhost:8080");
    // Set cookies to false
    js.executeScript("document.cookie = \'1=false\';document.cookie = \'2=false\';document.cookie = \'3=false\';");
    // Press the Feed-A-Cat link
    driver.findElement(By.linkText("Feed-A-Cat")).click();
    // Enter 6 into catnips input
    driver.findElement(By.id("catnips")).sendKeys("6");
    // Press the Feed button
    driver.findElement(By.xpath("//button[contains(text(), \'Feed\')]")).click();
    // Wait for Nom, nom, nom text to appear
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.textToBe(By.id("feedResult"), "Nom, nom, nom."));
    }
    // Check Nom, nom, nom message
    assertThat(driver.findElement(By.id("feedResult")).getText(), is("Nom, nom, nom."));
  }
  @Test
  public void tEST10GREETACAT() {
    // Open the target URL
    driver.get("http://localhost:8080");
    // Set cookies to false
    js.executeScript("document.cookie = \'1=false\';document.cookie = \'2=false\';document.cookie = \'3=false\';");
    // Press the Greet-A-Cat link
    driver.findElement(By.linkText("Greet-A-Cat")).click();
    // Check three Meow!s appear
    {
      List<WebElement> elements = driver.findElements(By.xpath("//*[contains(text(), \'Meow!Meow!Meow!\')]"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST11GREETACATWITHNAME() {
    // Navigate to greet-a-cat with Jennyanydots
    driver.get("http://localhost:8080/greet-a-cat/Jennyanydots");
    // Set cookies to false
    js.executeScript("document.cookie = \'1=false\';document.cookie = \'2=false\';document.cookie = \'3=false\';");
    // Check Meow! from Jennyanydots appears
    {
      List<WebElement> elements = driver.findElements(By.xpath("//*[contains(text(), \'Meow! from Jennyanydots.\')]"));
      assert(elements.size() > 0);
    }
  }
}